[package]
name = "thermite"
description = "Another rust chess engine"
categories = ["games", "command-line-utilities"]
authors.workspace = true
repository.workspace = true
keywords.workspace = true
version.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uci_driver = { path = "./uci_driver" }
thermite_search = { path = "./thermite_search", features = ["q_search", "move_ordering", "transposition_table", "progress_reporting", "multipv", "opening_book", "reductions", "pruning", "aspiration_windows"] }

[workspace]
members = [
    ".",
    "thermite_core",
    "thermite_movegen",
    "thermite_evaluation",
    "thermite_search",
    "uci_driver",
]

[workspace.package]
authors = ["Jeffrey Meyer <itotallyrock>"]
repository = "https://github.com/itotallyrock/thermite"
keywords = ["chess"]
version = "0.1.0"
edition = "2021"
license-file = "./LICENSE.md"
readme = "./README.md"