[package]
name = "thermite"
description = "Another rust chess engine"
version = "0.1.0"
edition = "2021"
authors = ["Jeffrey Meyer <itotallyrock>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
arrayvec = "0.7.2"
nom = "7.1.1"
num_enum = "0.5.7"
thiserror = "1.0.31"
threadpool = "1.8.1"

[dev-dependencies]
test-case = "2.1.0"
