[package]
name = "thermite"
description = "Another rust chess engine"
version = "0.1.0"
edition = "2021"
authors = ["Jeffrey Meyer <itotallyrock>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uci_driver = { path = "./uci_driver" }
thermite_search = { path = "./thermite_search" }

[workspace]
members = [
    ".",
    "thermite_core",
    "thermite_movegen",
    "thermite_evaluation",
    "thermite_search",
    "uci_driver",
]