[package]
name = "thermite_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["q_search", "move_ordering", "transposition_table", "progress_reporting", "multipv"]
q_search = ["thermite_movegen/q_moves", "thermite_core/static_exchange_eval"]
move_ordering = ["killer_heuristic", "history_heuristic"]
transposition_table = ["thermite_core/zobrist"]
killer_heuristic = []
history_heuristic = []
progress_reporting = [] # To support UCI info commands
pondering = []
multipv = []

[dependencies]
thermite_core = { path = "../thermite_core", default-features = false, features = ["chess_960", "repetitions"] }
thermite_movegen = { path = "../thermite_movegen", default-features = false }
thermite_evaluation = { path = "../thermite_evaluation", default-features = false }