[package]
name = "thermite_core"
description = "The foundation library for the Thermite chess engine. Chess essential types and functionality."
categories = ["games", "algorithms"]
authors.workspace = true
repository.workspace = true
keywords.workspace = true
version.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
chess_960 = []
repetitions = []
zobrist = []
nnue_accumulator = []
score = []
material_eval = ["score"]
piece_square_eval = ["score"]
hashable_chess_move = []

[dependencies]
derive_more = "0.99.17"
parse-display = "0.8.0"
lazy_static = "1.4.0"

[dev-dependencies]
test-case = "2.2.1"